### ISSUE TITLE
procedure for Ascent/Entry ES1

### ISSUE THREAD

**Issue by mdbernard** [intern-space-program/ksp#39]
Create a fine-grained procedure for ES1 ([references this comment](https://github.com/intern-space-program/ksp/issues/15#issuecomment-650439364)). Add as a markdown file in `proc/ascent-entry/ES1.md`. Reference [RPOD ES4 Procedure](https://github.com/intern-space-program/ksp/blob/trunk/proc/rpod/ES4.md).

**Comment by jdc-pub** [comment]
@mdbernard Can you clarify the ES1 and TO1 terminology in the comments you referenced?

I'm guessing...

* TO1 --> Take-Over Point 1

* ES1 --> Event Sequence 1

Are Event Sequences specific to each team (e.g. ascent-entry has an ES1, rpod has an ES1, etc.), or are Event Sequences unique mission-wide?

**Comment by mdbernard** [comment]
@cadojo Yes, you've got those right. TO = Take-Over Point, ES = Event Sequence, HO = Hand-Over Point. Is it clunky terminology? Yes. Does it fully describe what's happening? Also yes 😅. I'll make sure to bring this up at our next team meeting.

Event sequence numbers start at 1 for each team. If you look in [src/sequence_controllers](https://github.com/intern-space-program/ksp/tree/trunk/src/sequence_controllers), you can see there's another number near the start of those filenames which defines the execution order for the mission. The event sequence numbers are effectively just a tool to help chunk up each team's timeline to make things feel more manageable.

**Comment by jdc-pub** [comment]
Preliminary design outlined in [PR#60](https://github.com/intern-space-program/ksp/pull/60).
