### ISSUE TITLE
add documentation on ascent/entry trajectory estimation

### ISSUE THREAD

**Issue by mdbernard** [intern-space-program/ksp#4]

**Comment by jdc-pub** [comment]
@mdbernard thanks for setting all this up! Here are a couple resources off the bat. I will be adding more, so let's not close this issue just yet. I was going to add this information in a bit more detail in a wiki, I had a wiki page open but now it seems the option has disappeared. Thoughts on adding that back? I think it could be a useful place to document references, and figure out ascent/entry/TLI calculations, etc. 

* [Powerpoint slides from Launch and Entry Vehicle Design (ENAE791)](https://drive.google.com/drive/folders/1409Zc_5S17QR7FmR4_JNhao1QOFu4pAA?usp=sharing)

* [Jupyter Notebook with Planar Launch State Equations, and propagator Python example](https://gist.github.com/cadojo/31b76538ed1452ec7450ccf9ff1f948f)

**Comment by mdbernard** [comment]
Ah I disabled the Wiki. I didn't realize there was anything on it already. I think in order to keep things simple, we should just include links in a README.md in a doc directory containing all those files.

**Comment by mdbernard** [comment]
I'm going to add these docs directly to this repo for now. In the event that the repo size blows up, I'll create a new repo in the org containing reference docs and just link to it from a README. Ideally we'll avoid relying on storing reference docs in external locations.
