### ISSUE TITLE
procedure for Ascent/Entry ES2

### ISSUE THREAD

**Issue by mdbernard** [intern-space-program/ksp#40]
Create a fine-grained procedure for ES2 ([references this comment](https://github.com/intern-space-program/ksp/issues/15#issuecomment-650439364)). Add as a markdown file in `proc/ascent-entry/ES2.md`. Reference [RPOD ES4 Procedure](https://github.com/intern-space-program/ksp/blob/trunk/proc/rpod/ES4.md).

**Comment by jdc-pub** [comment]
Preliminary design outlined in [PR#60](https://github.com/intern-space-program/ksp/pull/60).
