### ISSUE TITLE
requirements.txt has an invalid numpy version number?

### ISSUE THREAD

**Issue by wcyoung08** [intern-space-program/ksp#54]
I tried to install numpy and the requirements.txt points to version 1.18.5, but it looks like from the numpy github that there never was a 1.18.5? I was looking here: https://github.com/numpy/numpy/releases

**Comment by jdc-pub** [comment]
Just issued a pull request that should fix this. I got it working by...

1. Making sure I was using python3.8
2. Running `python3.8 -m pip install -r requirements.txt`

If your default Python version is python3.8, and you have `pip` installed, you can simply run `pip install -r requirements.txt` in step 2.

I've updated `README.md` with this added `-r` option. Please let me know if this doesn't fix the issue for you! The pull request currently needs one reviewer.

**Comment by jdc-pub** [comment]
Adding the `-r` option in the comment above seems to install the dependencies correctly on `trunk`. @wcyoung08 could you confirm that option works for you? MR #55 should fix the issue, and is just waiting on a review before merge.

When I run `python3.8 -m pip install -r requirements.txt`, I get the following output:
```
Requirement already satisfied: cycler==0.10.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (0.10.0)
Requirement already satisfied: kiwisolver==1.2.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (1.2.0)
Requirement already satisfied: krpc==0.4.8 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (0.4.8)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (3.2.2)
Requirement already satisfied: numpy==1.18.5 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (1.18.5)
Requirement already satisfied: protobuf==3.12.2 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (3.12.2)
Requirement already satisfied: pyparsing==2.4.7 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (2.4.7)
Requirement already satisfied: python-dateutil==2.8.1 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (2.8.1)
Requirement already satisfied: six==1.15.0 in /usr/local/lib/python3.8/site-packages (from -r requirements.txt (line 10)) (1.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.8/site-packages (from protobuf==3.12.2->-r requirements.txt (line 7)) (46.0.0)
```

**Comment by wcyoung08** [comment]
So the problem I had seemed to stem from the fact that I am running windows, but did all this installation through a bash terminal using Windows subsystem for Linux, which had a different installation of python. I updated that, and then it looked like the command worked.
